name: dart_ml
description: Machine learning with dart
version: 0.0.1
author: Ilya Gyrdymov <ilgyrd@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  vector_math: any

dev_dependencies:
  test: ^0.12.0
