name: dart_ml
description: Machine learning with dart
version: 0.6.0
author: Ilya Gyrdymov <ilgyrd@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  csv: "^3.1.2"

dev_dependencies:
  benchmark_harness: ">=1.0.0 <2.0.0"
  test: ^0.12.0
