name: ml_algo
description: Machine learning algorithms written in native dart
version: 12.1.1
author: Ilia Gyrdymov <ilgyrd@gmail.com>
homepage: https://github.com/gyrdym/ml_algo

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  ml_dataframe: ^0.0.8
  ml_linalg: ^12.0.2
  quiver: ^2.0.2
  tuple: ^1.0.2
  xrange: 0.0.8

dev_dependencies:
  benchmark_harness: '>=1.0.0 <2.0.0'
  build_runner: ^1.1.2
  build_test: ^0.10.2
  grinder: ^0.8.3
  ml_tech: ^0.0.8
  mockito: ^3.0.0
  test: ^1.2.0
