name: dart_ml
description: Machine learning with dart
version: 1.0.0
author: Ilya Gyrdymov <ilgyrd@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  csv: ^4.0.0
  linalg:
    path: ../linalg
#    git:
#      url: https://github.com/gyrdym/linalg.git

dev_dependencies:
  benchmark_harness: ">=1.0.0 <2.0.0"
  test: ^1.2.0
  mockito: ^3.0.0
  build_runner: ^0.10.0
  build_test: ^0.10.2
