name: ml_algo
description: Machine learning algorithms written in native dart (without bindings to any popular ML libraries, pure Dart implementation)
version: 4.0.0
author: Ilia Gyrdymov <ilgyrd@gmail.com>
homepage: https://github.com/gyrdym/ml_algo

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  csv: ^4.0.0
  ml_linalg: ^4.0.0

dev_dependencies:
  benchmark_harness: ">=1.0.0 <2.0.0"
  test: ^1.2.0
  mockito: ^3.0.0
  build_runner: ^1.1.2
  build_test: ^0.10.2
