name: ml_algo
description: Popular machine learning algorithms with native dart (without bindings to any platforms)
version: 3.5.2
author: Ilia Gyrdymov <ilgyrd@gmail.com>
homepage: https://github.com/gyrdym/ml_algo

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  csv: ^4.0.0
  ml_linalg: ^2.0.0

dev_dependencies:
  benchmark_harness: ">=1.0.0 <2.0.0"
  test: ^1.2.0
  mockito: ^3.0.0
  build_runner: ^0.10.0
  build_test: ^0.10.2
